apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders-poc1
spec:
  host: http-db-service-poc1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2