apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders-poc2
spec:
  host: http-db-service-poc2
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1