apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders
spec:
  hosts:
    - "*"
  gateways:
    - orders-gateway
  http:
#  - match:
#    - uri:
#        exact: /orders
#    route:
#    - destination:
#        host: http-db-service
#        port:
#          number: 8017
  - match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: http-db-service
        subset: v1
  - match:
    - headers:
        end-user:
          exact: freddy
    route:
    - destination:
        host: http-db-service
        subset: v2