apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-poc2
spec:
  hosts:
    - "*"
  gateways:
    - orders-poc2-gateway
  http:
  - match:
    - uri:
        prefix: /p2/
    route:
    - destination:
        host: http-db-service-poc2
        port:
          number: 8017

