apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: postgres-instance-binding
  labels: 
    example: service-binding-service   
spec:
  instanceRef:
    name: postgres-instance

---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: postgres-instance-binding-usage
  labels:
    example: service-binding-service
spec:
 serviceBindingRef:
   name: postgres-instance-binding
 usedBy:
   kind: deployment
   name: http-db-service